targets:
  $default:
    builders:
      stanza_entity_builder|stanza_entity:
        enabled: true

builders:
  table:
    target: ":stanza_entity_builder"
    import: "package:stanza/src/builder/stanza_entity_builder.dart"
    builder_factories: ["StanzaEntityBuilder"]
    build_extensions: {".dart": [".stanza_entity.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]