name: stanza
author: "Kirk Linkletter <kirklinkletter@gmail.com>"
homepage: "https://github.com/kirklink/stanza"
description: "Library for building PostgreSQL queries."
version: 0.0.3
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  json_annotation: '^2.4.0'
  postgres: '^2.0.0-dev1.0'
  pool: '^1.4.0'
  bottom_line: '^0.0.3'
dev_dependencies:
  json_serializable: '^3.0.0'
  build_runner: any
  