targets:
  $default:
    builders:
      stanza_builder|stanza_entity:
        enabled: true
      stanza_builder|stanza_cellar:
        enabled: true

builders:
  stanza_entity:
    target: ":stanza_builder"
    import: "package:stanza_builder/builder.dart"
    builder_factories: ["stanzaBuilder"]
    build_extensions: {".dart": [".stanza.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]

  stanza_cellar:
    target: ":stanza_builder"
    import: "package:stanza_builder/builder.dart"
    builder_factories: ["cellarCollectionBuilder"]
    build_extensions: {".dart": [".cellar.dart"]}
    auto_apply: dependents
    build_to: source
