name: stanza_builder
author: "Kirk Linkletter <kirklinkletter@gmail.com>"
homepage: "https://github.com/kirklink/stanza"
description: "Library for building PostgreSQL queries. This is the code generator."
version: 0.0.8
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  source_gen: ^0.9.0
  build: '>=0.12.0 <2.0.0'
  analyzer: '^0.38.0'
  stanza: '^0.0.7'
  recase: '^2.0.1'
dev_dependencies:
  build_runner: any
  