name: stanza_builder
homepage: "https://github.com/kirklink/stanza"
description: "Library for building PostgreSQL queries. This is the code generator."
version: 0.0.24
environment:
  sdk: '>=2.8.0 <3.0.0'
dependencies:
  # stanza: ^0.0.24
  stanza:
    git: 
      url: https://github.com/kirklink/stanza.git
      ref: upgrade
      path: stanza
  source_gen: ^0.9.0
  build: ^1.2.2
  analyzer: ^1.5.0
  recase: ^3.0.0
dev_dependencies:
  build_runner: any
  