name: stanza
homepage: "https://github.com/kirklink/stanza"
description: "Library for building PostgreSQL queries in a Dart-y, type safe syntax that converts between Dart classes and Postgresql tables."
version: 0.0.21
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  postgres: '^2.1.1'
  pool: '^1.4.0'
  recase: '^3.0.0'
dev_dependencies:
  build_runner: any
  pedantic: any
  