name: stanza
homepage: "https://github.com/kirklink/stanza"
repository: "https://github.com/kirklink/stanza"
description: >-
  Library for building PostgreSQL queries in a Dart-y, type safe syntax
  that converts between Dart classes and PostgreSQL tables.
version: 0.1.0
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  postgres: ^3.4.0
dev_dependencies:
  build_runner: ^2.4.0
  lints: ^4.0.0
  test: ^1.24.0
