name: stanza_example
description: "Example of Stanza library usage."
version: 0.0.1
environment:
  sdk: '>=2.1.0 <3.0.0'
dependencies:
  stanza: any
dev_dependencies:
  build_runner: any
  stanza_builder: any